baseURL = "https://dkgo003.github.io/study_summary/"
locale = "ko-KR"
title = "Study Summary"

defaultContentLanguage = "ko"
enableRobotsTXT = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
